# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-05-19 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20240517_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(upload_to='project_bookstore/media'),
        ),
    ]
